trigger:
  - sendToGithub

pool:
  vmImage: 'ubuntu-latest'

steps:
  - bash: |
      git remote add secondary https://$TCX_GITHUB_TOKEN@github.com/appirio-tech/adoext-sync-test.git
      git push secondary HEAD:refs/heads/from-ADO --force --q
    env:
      TCX_GITHUB_TOKEN: $(TCX_GITHUB_TOKEN)
    displayName: 'Push To GitHub'
