name: Branch Synchronization - TCX

on:
  push:
    branches: [ from-ADO ]
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Push to Azure DevOps
        run: |
          git remote add secondary https://${{ secrets.TCX_AZURE_PAT }}@dev.azure.com/Lazybaer/Lazybaer01/_git/RedwoodSource
          git push secondary HEAD:refs/heads/sendToGithub --force --q